# ML Model Selection

This notebook is used for selecting a best ML model to apply into BigQuery ML. Since BigQuery ML cost is high for many iterations of model training, we use local for training ML because it will not incur any cost.

We don't pick model directly from local since our goal is to use BigQuery ML. We just pick model parameters and apply it into BigQuery ML.

For reference, we will compare only 3 models:

| Machine Learning | Sklearn | BQML |
| --- | --- | --- |
| Linear Regression | `Ridge` | `LINEAR_REG` |
| Random Forest | `XGBRFRegressor` | `RANDOM_FOREST_REGRESSOR` |
| Gradient Boosting | `XGBRegressor` | `BOOSTED_TREE_REGRESSOR` |

In [3]:
# import library
import pandas as pd
from pathlib import Path

# Data Preparation

In [8]:
# load data
path = Path.cwd() / ".." / "results" / "benchmark_results.csv"
df = pd.read_csv(path)

# show data
df.head()

,tier_months,variant,query_id,has_partition,has_cluster,table_size_bytes,partition_filter_ratio,cluster_filter_ratio,bytes_processed
0,2,none,1,False,False,1201852092,0.017544,0.047572,128179760
1,2,none,2,False,False,1201852092,0.017544,0.015565,128179760
2,2,none,3,False,False,1201852092,0.017544,0.001544,128179760
3,2,none,4,False,False,1201852092,0.017544,0.000344,128179760
4,2,none,5,False,False,1201852092,0.017544,0.000094,128179760

In [12]:
# divide columns into numerical and categorical
numerical_cols = ["table_size_bytes", "partition_filter_ratio", "cluster_filter_ratio", "bytes_processed"]
categorical_cols = ["has_partition", "has_cluster"]

# show descriptive statistics
print("Descriptive statistics for numerical columns:")
display(df[numerical_cols].describe())
print("\nDescriptive statistics for categorical columns:")
display(df[categorical_cols].describe())

Descriptive statistics for numerical columns:

,table_size_bytes,partition_filter_ratio,cluster_filter_ratio,bytes_processed
count,4.004000e+03,4004.000000,4004.000000,4.004000e+03
mean,5.142550e+09,0.288684,0.008848,2.145891e+08
std,1.806585e+09,0.261833,0.015482,2.507522e+08
min,1.201852e+09,0.002770,0.000000,1.884480e+05
25%,3.512204e+09,0.060345,0.000002,1.047894e+07
50%,5.998169e+09,0.200000,0.000340,8.972854e+07
75%,7.234807e+09,0.500000,0.015432,3.770166e+08
max,7.234807e+09,1.000000,0.047572,7.761573e+08

Descriptive statistics for categorical columns:

       has_partition has_cluster
count           4004        4004
unique             2           2
top            False       False
freq            2002        2002